export const SAVE_CARDS: string = 'SAVE_CARDS'
export const SET_TURNS: string = 'SET_TURNS'
export const SET_CHOICE_ONE: string = 'SET_CHOICE_ONE'
export const SET_CHOICE_TWO: string = 'SET_CHOICE_TWO'
export const SET_CURRENT_CARD_KEY: string = 'SET_CURRENT_CARD_KEY'
export const SET_PREV_CARD_KEY: string = 'SET_PREV_CARD_KEY'
